"""updated model

Revision ID: 39879fabc523
Revises: b1176ab26499
Create Date: 2026-02-21 17:32:09.834626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39879fabc523'
down_revision: Union[str, Sequence[str], None] = 'b1176ab26499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_number', sa.String(length=50), nullable=False),
    sa.Column('sponsor_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_applications_application_number'), 'drug_applications', ['application_number'], unique=True)
    op.create_table('drug_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('dosage_form', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=100), nullable=True),
    sa.Column('marketing_status', sa.String(length=100), nullable=True),
    sa.Column('product_ndc', sa.String(length=20), nullable=True),
    sa.Column('manufacturer_name', sa.String(length=255), nullable=True),
    sa.Column('rxcui', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['drug_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_products_application_id'), 'drug_products', ['application_id'], unique=False)
    op.create_index(op.f('ix_drug_products_brand_name'), 'drug_products', ['brand_name'], unique=False)
    op.create_index(op.f('ix_drug_products_generic_name'), 'drug_products', ['generic_name'], unique=False)
    op.create_index(op.f('ix_drug_products_product_ndc'), 'drug_products', ['product_ndc'], unique=True)
    op.create_index(op.f('ix_drug_products_rxcui'), 'drug_products', ['rxcui'], unique=False)
    op.create_table('drug_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('unii', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['drug_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_ingredients_product_id'), 'drug_ingredients', ['product_id'], unique=False)
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('safety_stock_level', sa.Integer(), nullable=True),
    sa.Column('predicted_days_to_zero', sa.Float(), nullable=True),
    sa.Column('predicted_risk_score', sa.Float(), nullable=True),
    sa.Column('last_restocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['drug_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'product_id', 'batch_number', name='unique_inventory_batch')
    )
    op.create_index(op.f('ix_inventories_hospital_id'), 'inventories', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_inventories_product_id'), 'inventories', ['product_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['drug_products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_product_id'), 'purchase_order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_purchase_order_id'), 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_table('supplier_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('price_per_unit', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['drug_products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'product_id', name='unique_supplier_product')
    )
    op.create_index(op.f('ix_supplier_products_id'), 'supplier_products', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_products_product_id'), 'supplier_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_supplier_products_supplier_id'), 'supplier_products', ['supplier_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['drug_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_logs_hospital_id'), 'usage_logs', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_id'), 'usage_logs', ['id'], unique=False)
    op.create_index(op.f('ix_usage_logs_product_id'), 'usage_logs', ['product_id'], unique=False)
    op.drop_index(op.f('ix_supplier_medicines_id'), table_name='supplier_medicines')
    op.drop_table('supplier_medicines')
    op.add_column('hospitals', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_purchase_orders_hospital_id'), 'purchase_orders', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.alter_column('suppliers', 'name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=250),
               existing_nullable=False)
    op.drop_column('suppliers', 'avg_delivery_days')
    op.drop_column('suppliers', 'reliability_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('reliability_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('avg_delivery_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('suppliers', 'name',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_hospital_id'), table_name='purchase_orders')
    op.drop_column('hospitals', 'updated_at')
    op.create_table('supplier_medicines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_unit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('supplier_medicines_supplier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('supplier_medicines_pkey'))
    )
    op.create_index(op.f('ix_supplier_medicines_id'), 'supplier_medicines', ['id'], unique=False)
    op.drop_index(op.f('ix_usage_logs_product_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_hospital_id'), table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index(op.f('ix_supplier_products_supplier_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_product_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_id'), table_name='supplier_products')
    op.drop_table('supplier_products')
    op.drop_index(op.f('ix_purchase_order_items_purchase_order_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_product_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_inventories_product_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_hospital_id'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_index(op.f('ix_drug_ingredients_product_id'), table_name='drug_ingredients')
    op.drop_table('drug_ingredients')
    op.drop_index(op.f('ix_drug_products_rxcui'), table_name='drug_products')
    op.drop_index(op.f('ix_drug_products_product_ndc'), table_name='drug_products')
    op.drop_index(op.f('ix_drug_products_generic_name'), table_name='drug_products')
    op.drop_index(op.f('ix_drug_products_brand_name'), table_name='drug_products')
    op.drop_index(op.f('ix_drug_products_application_id'), table_name='drug_products')
    op.drop_table('drug_products')
    op.drop_index(op.f('ix_drug_applications_application_number'), table_name='drug_applications')
    op.drop_table('drug_applications')
    # ### end Alembic commands ###
