"""updated model

Revision ID: b1176ab26499
Revises: a48903dd4ea5
Create Date: 2026-02-21 17:25:37.921681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1176ab26499'
down_revision: Union[str, Sequence[str], None] = 'a48903dd4ea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade():
    op.execute("DROP TABLE inventories CASCADE;")
    op.execute("DROP TABLE usage_logs CASCADE;")
    op.execute("DROP TABLE medicines CASCADE;")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_logs', sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usage_logs', type_='foreignkey')
    op.create_foreign_key(op.f('usage_logs_medicine_id_fkey'), 'usage_logs', 'medicines', ['medicine_id'], ['id'])
    op.drop_index(op.f('ix_usage_logs_product_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_hospital_id'), table_name='usage_logs')
    op.drop_column('usage_logs', 'product_id')
    op.add_column('suppliers', sa.Column('avg_delivery_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('reliability_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('suppliers', 'name',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_hospital_id'), table_name='purchase_orders')
    op.add_column('inventories', sa.Column('avg_daily_usage_7d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inventories', sa.Column('avg_daily_usage_30d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inventories', sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventories', type_='foreignkey')
    op.create_foreign_key(op.f('inventories_medicine_id_fkey'), 'inventories', 'medicines', ['medicine_id'], ['id'])
    op.drop_constraint('unique_inventory_batch', 'inventories', type_='unique')
    op.drop_index(op.f('ix_inventories_product_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_hospital_id'), table_name='inventories')
    op.create_unique_constraint(op.f('unique_hospital_medicine'), 'inventories', ['hospital_id', 'medicine_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_inventories_id'), 'inventories', ['id'], unique=False)
    op.drop_column('inventories', 'updated_at')
    op.drop_column('inventories', 'created_at')
    op.drop_column('inventories', 'batch_number')
    op.drop_column('inventories', 'product_id')
    op.drop_column('hospitals', 'updated_at')
    op.create_table('medicines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('generic_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('brand_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('drug_class', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dosage_form', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('strength', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('medicines_pkey'))
    )
    op.create_index(op.f('ix_medicines_name'), 'medicines', ['name'], unique=False)
    op.create_index(op.f('ix_medicines_id'), 'medicines', ['id'], unique=False)
    op.create_table('supplier_medicines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_unit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], name=op.f('supplier_medicines_medicine_id_fkey')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('supplier_medicines_supplier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('supplier_medicines_pkey'))
    )
    op.create_index(op.f('ix_supplier_medicines_id'), 'supplier_medicines', ['id'], unique=False)
    op.drop_index(op.f('ix_supplier_products_supplier_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_product_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_id'), table_name='supplier_products')
    op.drop_table('supplier_products')
    op.drop_index(op.f('ix_purchase_order_items_purchase_order_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_product_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_drug_ingredients_product_id'), table_name='drug_ingredients')
    op.drop_table('drug_ingredients')
    op.drop_index(op.f('ix_drug_products_rxcui'), table_name='drug_products')
    op.drop_index(op.f('ix_drug_products_product_ndc'), table_name='drug_products')
    op.drop_index(op.f('ix_drug_products_generic_name'), table_name='drug_products')
    op.drop_index(op.f('ix_drug_products_brand_name'), table_name='drug_products')
    op.drop_index(op.f('ix_drug_products_application_id'), table_name='drug_products')
    op.drop_table('drug_products')
    op.drop_index(op.f('ix_drug_applications_application_number'), table_name='drug_applications')
    op.drop_table('drug_applications')
    # ### end Alembic commands ###
